service: lbh-google-auth

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs18.x
  timeout: 30
  region: eu-west-2
  stage: ${opt:stage}
  lambdaHashingVersion: 20201221
  apiGateway:
    shouldStartNameWithService: true

functions:
  lbh-google-auth:
    name: ${self:service}-${self:provider.stage}
    handler: index.handler
    events:
      - http: ANY /
      - http: ANY /{proxy+}
    vpc:
      securityGroupIds: ${self:custom.securityGroups.${self:provider.stage}}
      subnetIds: ${self:custom.subnets.${self:provider.stage}}
    environment:
      ADMIN_OAUTH_CALLBACK_URL: ${env:ADMIN_OAUTH_CALLBACK_URL_${self:provider.stage}}
      ADMIN_REFRESH_TOKEN: ${env:ADMIN_REFRESH_TOKEN}
      COOKIE_DOMAIN: ${env:COOKIE_DOMAIN}
      JWT_SECRET: ${env:JWT_SECRET}
      OAUTH_CALLBACK_URL: ${env:OAUTH_CALLBACK_URL_${self:provider.stage}}
      OAUTH_CLIENT_ID: ${env:OAUTH_CLIENT_ID}
      OAUTH_CLIENT_SECRET: ${env:OAUTH_CLIENT_SECRET}

resources:
  Resources:
    CloudFrontDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          # Aliases:
          #   - ${self:custom.aliases.${self:provider.stage}}
          # PriceClass: PriceClass_100
          # ViewerCertificate:
          #   AcmCertificateArn: ${self:custom.certificate-arn.${self:provider.stage}}
          #   MinimumProtocolVersion: TLSv1.2_2018
          #   SslSupportMethod: sni-only
          DefaultCacheBehavior:
            TargetOriginId: ${self:service}-${self:provider.stage}-custom-origin
            ViewerProtocolPolicy: 'redirect-to-https'
            AllowedMethods:
              - GET
              - HEAD
              - OPTIONS
              - PUT
              - PATCH
              - POST
              - DELETE
            DefaultTTL: 0
            MaxTTL: 0
            MinTTL: 0
            ForwardedValues:
              QueryString: true
              Cookies:
                Forward: all
          Enabled: true
          Origins:
            - Id: ${self:service}-${self:provider.stage}-custom-origin
              DomainName: ${self:custom.domain-name}
              OriginPath: /${self:provider.stage}
              CustomOriginConfig:
                HTTPPort: 80
                HTTPSPort: 443
                OriginProtocolPolicy: https-only
    staticImagesBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: auth-test-dr-testing-static-images

custom:
  domain-name:
    Fn::Join:
      - '.'
      - - Ref: ApiGatewayRestApi
        - execute-api
        - eu-west-2
        - amazonaws.com
  # aliases:
  #   staging: auth-test.hackney.gov.uk
  # production: auth.hackney.gov.uk
  # certificate-arn:
  #   staging: arn:aws:acm:us-east-1:715003523189:certificate/ff86b046-eebb-421e-8581-50676bb28fb1
    # production: arn:aws:acm:us-east-1:851725205572:certificate/9d53fdf1-531a-4665-9cfd-e93e6961c7f4
  securityGroups:
    development:
      - sg-08e28776da7918e4b
    staging:
      - sg-0166cbf56b7e77af0
    production:
      - sg-07d5d1b647871ed04
  subnets:
    development:
      - subnet-0140d06fb84fdb547
      - subnet-05ce390ba88c42bfd
    staging:
      - subnet-06d3de1bd9181b0d7
      - subnet-0ed7d7713d1127656
    production:
      - subnet-05e595c59b7d6c8df
      - subnet-0e6bc9b4ac24493cc