version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:14

references:
  workspace_root: &workspace_root "~"
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

jobs:
  checkout:
    executor: node-executor
    steps:
      - *attach_workspace
      - checkout
      - persist_to_workspace:
          root: *workspace_root
          paths: .

  install-dependencies:
    executor: node-executor
    steps:
      - *attach_workspace
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - persist_to_workspace:
          root: *workspace_root
          paths: .

  unit-tests:
    executor: node-executor
    steps:
      - *attach_workspace
      - run:
          name: Run linting
          command: npm run lint
      - run:
          name: Run tests
          command: npm test

workflows:
  version: 2
  process-form-submission:
    jobs:
      - checkout
      - install-dependencies:
          requires:
            - checkout
      - unit-tests:
          requires:
            - install-dependencies
